name: ci

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node }}

      - name: Run deploy script
        run: |
          set -e
          
          npm run generate 

          cd dist

          echo '<domain>' > CNAME

          git init
          git add -A
          git commit -m 'deploy'

          git push -f git@github.com:tommytrg/website.git master:gh-pages